import React, { useState } from 'react';
import { Icon } from '../components/Icon';
import { StatusBadge, ContentTypeBadge, RegionBadge } from '../components/Badge';

export const AIDraftReviewPage = ({
  record,
  currentUser,
  onApproveAndPublish,
  onRequestChanges,
  onUpdateDraft,
  onOpenStudentView,
  onOpenOutreach,
  onBackToExplore
}) => {
  if (!record) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16 text-center space-y-4">
        <div className="w-12 h-12 rounded-full bg-slate-100 text-slate-400 mx-auto flex items-center justify-center">
          <Icon name="shield-check" size={24} />
        </div>
        <h2 className="text-xl font-bold text-slate-800">No Record Selected for Review</h2>
        <p className="text-xs text-slate-500">Please choose a pending record from the Explore page or Review Queue.</p>
        <button
          onClick={onBackToExplore}
          className="px-4 py-2 bg-blue-600 text-white text-xs font-semibold rounded-lg hover:bg-blue-700"
        >
          Go to Explore Records
        </button>
      </div>
    );
  }

  const [isEditing, setIsEditing] = useState(false);
  const [editedExplainerBody, setEditedExplainerBody] = useState(
    record.aiDraft?.studentExplainer?.bodyText || record.description
  );
  const [editedExplainerIntro, setEditedExplainerIntro] = useState(
    record.aiDraft?.studentExplainer?.intro || ''
  );
  const [editedCaption, setEditedCaption] = useState(
    record.aiDraft?.socialCaption?.body || ''
  );
  const [editedHashtags, setEditedHashtags] = useState(
    record.aiDraft?.socialCaption?.hashtags?.join(' ') || '#PolarScience #Antarctica #NCPOR'
  );
  const [reviewNotes, setReviewNotes] = useState(
    `Verified scientific claims against ${record.expeditionName}. Terminology and facts checked.`
  );

  const handleSaveEdits = () => {
    const updatedDraft = {
      ...record.aiDraft,
      studentExplainer: {
        ...record.aiDraft?.studentExplainer,
        intro: editedExplainerIntro,
        bodyText: editedExplainerBody
      },
      socialCaption: {
        ...record.aiDraft?.socialCaption,
        body: editedCaption,
        hashtags: editedHashtags.split(' ').map(t => t.startsWith('#') ? t : `#${t}`).filter(Boolean)
      }
    };
    onUpdateDraft(record.id, updatedDraft);
    setIsEditing(false);
  };

  const handleApprove = () => {
    onApproveAndPublish(record.id, reviewNotes);
  };

  const handleReject = () => {
    const notes = prompt("Enter reasons or required changes for the researcher:", "Please verify the ice core isotopic baseline depth values.");
    if (notes) {
      onRequestChanges(record.id, notes);
    }
  };

  const isAlreadyPublished = record.status === 'Published';

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-6">
      {/* Top Breadcrumb & Status */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <button
          onClick={onBackToExplore}
          className="text-xs font-semibold text-slate-500 hover:text-slate-800 flex items-center gap-1.5"
        >
          <Icon name="arrow-left" size={14} /> Back to Search / Records
        </button>

        <div className="flex items-center gap-2">
          <span className="text-xs text-slate-500">Record Status:</span>
          <StatusBadge status={record.status} />
        </div>
      </div>

      {/* Header matching Reference Screenshot */}
      <div>
        <div className="flex items-center gap-2 text-xs font-semibold text-blue-700 uppercase tracking-wide">
          <Icon name="shield-check" size={16} className="text-amber-500" />
          Mandatory Human Review Gate
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 mt-1">
          AI Draft (Review)
        </h1>
        <p className="text-xs sm:text-sm text-slate-500 mt-1">
          Here's the AI-generated student explainer and social media caption. Please review, edit if needed, and approve before publishing to the public portal.
        </p>
      </div>

      {/* AI Advisory Banner */}
      <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-blue-100 text-blue-700 shrink-0">
            <Icon name="sparkles" size={18} />
          </div>
          <div>
            <div className="font-bold text-blue-900">
              Generated by {record.aiDraft?.model || 'PolarAI-Assist (Advisory Adapter)'}
            </div>
            <p className="text-slate-600 text-[11px]">
              AI drafts are non-destructive and cannot overwrite verified scientific records. You are acting as: <strong>{currentUser.name}</strong> ({currentUser.role})
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          {!isEditing ? (
            <button
              onClick={() => setIsEditing(true)}
              className="px-3 py-1.5 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5 shadow-2xs"
            >
              <Icon name="edit" size={13} /> Edit AI Draft
            </button>
          ) : (
            <button
              onClick={handleSaveEdits}
              className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5"
            >
              <Icon name="check" size={13} /> Save Edited Draft
            </button>
          )}
        </div>
      </div>

      {/* Two Column Layout matching Reference Screenshot */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
        {/* Left Card: Source & Student Explainer */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden flex flex-col">
          {/* Header Card Strip */}
          <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center gap-3">
            <div className="p-2 rounded-lg bg-blue-100 text-blue-700">
              <Icon name="file-text" size={20} />
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <ContentTypeBadge type={record.contentType} />
                <RegionBadge region={record.region} />
              </div>
              <h3 className="font-bold text-sm text-slate-900 truncate mt-1">
                {record.title}
              </h3>
              <p className="text-[11px] text-slate-400 truncate">
                {record.expeditionName} • Author: {record.authorName || 'NCPOR Researcher'}
              </p>
            </div>
          </div>

          <div className="p-6 space-y-6 flex-1">
            {/* AI Generated Explainer Header */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <h4 className="font-bold text-xs uppercase tracking-wider text-slate-800 flex items-center gap-1.5">
                  <Icon name="book-open" size={15} className="text-teal-600" />
                  AI Generated Explainer (For Students & Public)
                </h4>
                <span className="text-[10px] bg-teal-50 text-teal-700 px-2 py-0.5 rounded font-medium border border-teal-200">
                  Plain Language
                </span>
              </div>

              {isEditing ? (
                <div className="space-y-3">
                  <div>
                    <label className="block text-[11px] font-semibold text-slate-600 mb-1">Intro Summary</label>
                    <textarea
                      rows={2}
                      value={editedExplainerIntro}
                      onChange={(e) => setEditedExplainerIntro(e.target.value)}
                      className="w-full text-xs p-2 bg-slate-50 border border-slate-300 rounded text-slate-800 focus:outline-none"
                    />
                  </div>
                  <div>
                    <label className="block text-[11px] font-semibold text-slate-600 mb-1">Detailed Explanation Body</label>
                    <textarea
                      rows={5}
                      value={editedExplainerBody}
                      onChange={(e) => setEditedExplainerBody(e.target.value)}
                      className="w-full text-xs p-2 bg-slate-50 border border-slate-300 rounded text-slate-800 focus:outline-none"
                    />
                  </div>
                </div>
              ) : (
                <div className="p-4 bg-slate-50 rounded-lg border border-slate-200 text-xs text-slate-700 space-y-2 leading-relaxed">
                  {record.aiDraft?.studentExplainer?.intro && (
                    <p className="font-medium text-slate-900 italic border-l-2 border-teal-500 pl-2">
                      "{record.aiDraft.studentExplainer.intro}"
                    </p>
                  )}
                  <p>
                    {record.aiDraft?.studentExplainer?.bodyText || record.aiDraft?.summary || record.description}
                  </p>
                </div>
              )}
            </div>

            {/* Key Takeaways Preview */}
            <div className="space-y-2">
              <h5 className="font-bold text-xs text-slate-800 flex items-center gap-1.5">
                <Icon name="check-circle" size={14} className="text-emerald-600" />
                Key Takeaways Draft
              </h5>
              <ul className="space-y-1.5 text-xs text-slate-600">
                {(record.aiDraft?.studentExplainer?.keyTakeaways || [
                  "Ice cores show past temperatures and atmospheric gas composition.",
                  "Help scientists predict future climate changes and polar trends.",
                  "Important for global sea-level and monsoon predictions."
                ]).map((k, idx) => (
                  <li key={idx} className="flex items-start gap-2 bg-emerald-50/50 p-2 rounded border border-emerald-100/60">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0"></span>
                    <span>{k}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Reviewer Note Input */}
            <div className="space-y-1.5 pt-2 border-t border-slate-100">
              <label className="block text-xs font-bold text-slate-700">
                Reviewer Audit Note / Sign-off Remarks
              </label>
              <input
                type="text"
                value={reviewNotes}
                onChange={(e) => setReviewNotes(e.target.value)}
                placeholder="Enter review remarks (saved into immutable audit log)..."
                className="w-full text-xs p-2.5 bg-white border border-slate-300 rounded-lg text-slate-800 focus:outline-none"
              />
            </div>
          </div>

          {/* Action Buttons matching Reference Screenshot */}
          <div className="p-4 bg-slate-50 border-t border-slate-200 flex flex-wrap items-center justify-between gap-3">
            <button
              onClick={() => setIsEditing(!isEditing)}
              className="px-4 py-2 bg-white border border-slate-300 hover:bg-slate-100 text-slate-700 rounded-lg text-xs font-semibold transition-colors flex items-center gap-1.5"
            >
              <Icon name="edit" size={14} />
              {isEditing ? "Cancel Edit" : "Edit Draft"}
            </button>

            <div className="flex items-center gap-2">
              <button
                onClick={handleReject}
                className="px-3.5 py-2 bg-white border border-rose-300 text-rose-700 hover:bg-rose-50 rounded-lg text-xs font-semibold transition-colors flex items-center gap-1"
              >
                <Icon name="x-circle" size={14} />
                Request Changes
              </button>

              <button
                onClick={handleApprove}
                className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold shadow-xs transition-colors flex items-center gap-1.5"
              >
                <Icon name="shield-check" size={15} />
                {isAlreadyPublished ? "Re-Approve & Save" : "Approve & Publish"}
              </button>
            </div>
          </div>
        </div>

        {/* Right Card: AI Generated Social Media Caption */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden flex flex-col">
          <div className="p-4 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
            <h3 className="font-bold text-xs uppercase tracking-wider text-slate-800 flex items-center gap-1.5">
              <Icon name="share" size={15} className="text-purple-600" />
              AI Generated Social Media Caption
            </h3>
            <span className="text-[10px] bg-purple-50 text-purple-700 px-2 py-0.5 rounded font-medium border border-purple-200">
              Ready-to-Post Pack
            </span>
          </div>

          <div className="p-6 space-y-5 flex-1">
            {/* Social Post Preview Box */}
            <div className="border border-slate-200 rounded-xl p-4 bg-white shadow-2xs space-y-3">
              {/* Account Header */}
              <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-full bg-blue-600 flex items-center justify-center text-white font-bold text-xs">
                  <Icon name="polar-logo" className="w-5 h-5" />
                </div>
                <div>
                  <div className="flex items-center gap-1">
                    <span className="font-bold text-xs text-slate-900">PolarSetu India</span>
                    <span className="text-[10px] text-blue-500 font-semibold">✓</span>
                  </div>
                  <span className="text-[10px] text-slate-400">@PolarSetu • Official Outreach</span>
                </div>
              </div>

              {/* Caption Content */}
              {isEditing ? (
                <div className="space-y-2">
                  <label className="block text-[11px] font-semibold text-slate-600">Edit Social Caption</label>
                  <textarea
                    rows={4}
                    value={editedCaption}
                    onChange={(e) => setEditedCaption(e.target.value)}
                    className="w-full text-xs p-2 bg-slate-50 border border-slate-300 rounded text-slate-800 focus:outline-none"
                  />
                  <input
                    type="text"
                    value={editedHashtags}
                    onChange={(e) => setEditedHashtags(e.target.value)}
                    className="w-full text-xs p-2 bg-slate-50 border border-slate-300 rounded text-slate-800 focus:outline-none"
                    placeholder="#Hashtags"
                  />
                </div>
              ) : (
                <div className="text-xs text-slate-800 space-y-2 leading-relaxed">
                  <p className="font-semibold text-blue-900">
                    {record.aiDraft?.socialCaption?.hook || "🧊 Ice tells a story!"}
                  </p>
                  <p className="text-slate-700">
                    {record.aiDraft?.socialCaption?.body || record.aiDraft?.summary || record.description}
                  </p>
                  <div className="text-blue-600 font-medium text-xs">
                    {record.aiDraft?.socialCaption?.hashtags?.join(' ') || "#PolarScience #Antarctica #ClimateResearch #NCPOR"}
                  </div>
                </div>
              )}

              {/* Image Preview */}
              <div className="rounded-lg overflow-hidden border border-slate-200 bg-slate-100 max-h-48">
                <img
                  src={record.thumbnail}
                  alt={record.title}
                  className="w-full h-48 object-cover"
                />
              </div>

              <div className="text-[10px] text-slate-400 flex items-center justify-between pt-1">
                <span>Alt Text: {record.aiDraft?.socialCaption?.altText?.slice(0, 50)}...</span>
                <span>Auto-drafted • Editable</span>
              </div>
            </div>

            {/* Quick Actions if Published */}
            {isAlreadyPublished && (
              <div className="p-3.5 bg-emerald-50 rounded-lg border border-emerald-200 space-y-2">
                <div className="text-xs font-bold text-emerald-900 flex items-center gap-1.5">
                  <Icon name="check-circle" size={15} />
                  Record is Published & Active
                </div>
                <div className="flex items-center gap-2 pt-1">
                  <button
                    onClick={() => onOpenStudentView(record)}
                    className="px-3 py-1.5 bg-teal-600 hover:bg-teal-700 text-white rounded text-xs font-medium"
                  >
                    View Student Explainer
                  </button>
                  <button
                    onClick={() => onOpenOutreach(record)}
                    className="px-3 py-1.5 bg-purple-600 hover:bg-purple-700 text-white rounded text-xs font-medium"
                  >
                    Open Outreach Studio
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
